Repository jelwingeuan/University-Appointment-System-UAS-, pull requests merged in 2024-06, with the labels that each got.

#119 v1.6.3_signinform_realfacname <Actual Faculty Name Options on Sign Up > (2024.06.01, 18:01)
  app.py
  database.db
  templates/signup.html
Labels: documentation, done, tested

#120 v1.6.4_calendar_logicrewrite (2024.06.02, 00:07)
  app.py
  create_tables.py
  lecturer_calendar.py
  tempCodeRunnerFile.py
Labels: bug, feature, help wanted, fix

#121 v1.6.5_signup_emailverify <Specific Email Required For Sign Up> (2024.06.02, 1:16)
  app.py
  database.db
  templates/signup.html
Labels: documentation, done, tested

#123 v1.6.7_chores <Reput "pin.json"> (2024.06.02, 20:04)
  database.db
  pin.json
Labels: fixed, tested

#124 v1.6.8_facultylist_stulec <Faculty List w/ Students and Lecturer> (2024.06.03, 0:35)
  app.py
  templates/Faculty.html
Labels: documentation, feature, fix, done, tested

#127 v1.7.1_calendar_repeat (2024.06.04 15:43)
  app.py
  database.db
  lecturer_calendar.py
Labels: documentation, feature, not yet finished, fix

#128 v1.7.2_mani_email <Changed The Domain Of The Email> (2024.06.05, 19:13)
  app.py
  templates/signup.html
Labels: fix, done, tested

#129 v1.7.3_ifdataexisted_sigup <User Feedback On Name&Email> (2024.06.06, 0:00)
  app.py
  database.db
  templates/signup.html
Labels: documentation, feature, done, tested

#130 v1.7.4_ifdataexited_hp <User Feedback On Phone Number> (2024.06.06, 18:39)
  app.py
  database.db
Labels: documentation, done, tested

#131 v1.7.5_route_revised <Removed createfacultyhub From Nav Bar> (2024.06.06, 20:59)
  database.db
  static/faculty_pp/jpeg
  templates/Faculty.html
  templates/admin.html
  templates/adminpageeditor.html
  templates/appointment_control.html
  templates/createfacultyhub.html
  templates/usercontrol.html
Labels: documentation

#132 v1.7.6_adminjson <Transfered Admin's Email & Password Into A Json>(2024.06.07, 20:35)
  admin.json
  app.py
Labels: done

#138 debug_1 <Small Tweak> (2024/06/09, 11:03)
  database.db
  templates/appointment.html
  templates/appointment2.html
Labels: fix, done

#142 v1.8.4_testing1 <Testing 1> (2024.06.10,19:17)
  admin.json
  database.db
  pin.json
  static/faculty_pp/298784174_557053909542304_4033589964657281644_n.jpg
  static/faculty_pp/305069688_577714670676654_6454183285070282029_n.png
  static/faculty_pp/faculty_of_engineering_multimedia_university_logo.jpeg
  static/faculty_pp/images.jpeg
Labels: bug, fix

#144 debug2 <Added Runtime For Deployment> (2024.06.10, 19:37)
  runtime.txt
Labels: done

#145 v.2.0.0_deploy "updated database" (2024.06.10, 20:10)
  database.db
Labels: done

#146 v2.0.1_Procfile "Procfile for Heroku"
  Procfile
Labels: done, fixed

#147 v2.0.2_gunicorn "
  requirements.txt
Labels: done

#148 v2.0.3_resetdatabase
  database.db
Labels: done

#158 Added Flash for Incorrections
  templates/login.html
Labels: documentation, done

#159 v2.0.9_adminpageeditor "Revised adminpageeditor" (2024.06.11, 11:38)
  app.py
  templates/adminpageeditor.html
Labels: documentation, done, fixed, tested

#160 v2.0.10_database1 "Upadated Database 1" (2024.06.11, 12:00)
  database.db
  templates/createfacultyhub.html
Labels: documentation

#162 added csv files
  appointments.csv
  calendar.csv
  csve.py
  facultyhub.csv
  users.csv
Labels: documentation

#163 csv updated and facultyhub to hub
  app.py
  create_tables.py
  csve.py
  database.db
  facultyhub.csv
  hub.csv
  templates/Faculty.html
  templates/createhub.html
Labels: documentation

#164 added supabase env file but shit table still not update it
  .env
  appointments.csv
  calendar.csv
  database.db
  db_functions.py
Labels: bug

#166 added dotenv in requirements
  requirements.txt
Labels: documentation

#169 Base comment
  admin.json
  pin.json
  requirements.txt
Labels: documentation, done, fixed

#173 V2.1.3 data upadate
  database.db
Labels: done
