Repository jelwingeuan/University-Appointment-System-UAS-, pull requests merged in 2024-04, with the labels that each got.

#2 v1.0.2 (12.04.2024, 1:20)
  BACKEND/__pycache__/views.cpython-311.pyc
  BACKEND/app.py
  BACKEND/justest.py
  BACKEND/tempCodeRunnerFile.py
  BACKEND/templetes/home.html
  BACKEND/templetes/login.html
  BACKEND/views.py
Labels: bug, not yet finished

#14 v1.0.8 (2024.04.18)
  website/__pycache__/app.cpython-311.pyc
  website/__pycache__/models.cpython-311.pyc
  website/__pycache__/routes.cpython-311.pyc
  website/__pycache__/views.cpython-311.pyc
  website/app.py
  website/models.py
  website/routes.py
Labels: bug, help wanted, not yet finished

#17 v1.0.9 (2024.04.18, 20:33)
  website/__pycache__/models.cpython-311.pyc
  website/__pycache__/routes.cpython-311.pyc
  website/app.py
  website/models.py
  website/routes.py
  website/static/myscripts.js
  website/static/style.css
  website/templates/myscripts.js
  website/views.py
Labels: documentation, fix

#29 v1.0.19 (2024.04.23, 12:41)
  .vscode/launch.json
  __pycache__/app.cpython-311.pyc
  __pycache__/models.cpython-311.pyc
  __pycache__/routes.cpython-311.pyc
  __pycache__/user_authentication.cpython-311.pyc
  __pycache__/user_authentication.cpython-312.pyc
  __pycache__/views.cpython-312.pyc
  app.py
  templates/login.html
  views.py
Labels: bug, documentation, fix

#37 v1.1.1_booking1 (Booking System)
  __pycache__/app.cpython-312.pyc
  __pycache__/user_authentication.cpython-312.pyc
  booking.py
Labels: feature, not yet finished

#42 v1.1.4_book2 <Booking System> (2024.04.28, 16:05)
  app.py
  booking.py
  templates/invoice.html
  user_authentication.py
Labels: documentation, feature, not yet finished

#43 v1.1.5_book2 <Booking System> (2024.04.28, 18:29)
  app.py
  booking.py
  user_authentication.db
Labels: documentation, feature

#46 v1.1.8_db_fix <app & user_auth fix>
  __pycache__/db_functions.cpython-312.pyc
  app.py
Labels: feature, fixed

#47 v1.1.9_signup_intertodb <Fixing signup database schema issue> (2024.04.29, 10:07)
  __pycache__/app.cpython-312.pyc
  __pycache__/db_functions.cpython-311.pyc
  __pycache__/db_functions.cpython-312.pyc
  app.py
  create_tables.py
  db_functions.py
  templates/signup.html
Labels: bug, documentation, feature, not yet finished, fix

#50 v1.1.11_login <Stabilized Fundamental Signup & Login Functions> (2024.04.29, 21:16)
  __pycache__/db_functions.cpython-311.pyc
  __pycache__/db_functions.cpython-312.pyc
  app.py
  database.db
Labels: documentation, feature, done, fixed, tested

#53 v1.1.13_Intergrate_Admin_MessageFlash_Appointment <Intergration on Admin, Msg, Appointment> (2024.04.30, 08:01)
  app.py
  database.db
Labels: feature, done, fixed

#54 v1.1.14_port <Port & Msg Changes> (2024.04.30, 13:00)
  app.py
  database.db
Labels: documentation, done, tested
