Repository jelwingeuan/University-Appointment-System-UAS-, pull requests merged in 2024-05, with the labels that each got.

#57 v1.2.1_admin_fac <Fund. templates of Create Faculty Hub> (2024.05.01, 23:32)
  __pycache__/app.cpython-312.pyc
  app.py
  templates/admin.html
Labels: documentation, feature, help wanted, not yet finished, fix

#58 v1.2.2_admin_fac <Added create_faculty_hub page> (2024.05.02, 22:50)
  app.py
  templates/admin.html
  templates/create_faculty_hub.html
Labels: documentation, feature, help wanted, question, not yet finished, fix

#60 v1.2.4_admin_fac <Hub creator intergrated into db> (2024.05.04, 01:47)
  app.py
  create_tables.py
  database.db
  templates/create_faculty_hub.html
Labels: documentation, feature, question, not yet finished

#62 v1.2.6_admin_fac <Correction Made> (2024.05.04, 18:04)
  database.db
  templates/addfaculty.html
  templates/create_faculty_hub.html
Labels: fixed

#65 v1.2.7_admin_fac_creator <Still fixing why the hell i can't store into "facultyhub" table> (2024.05.05, 01:37)
  app.py
  create_tables.py
  database.db
  templates/admin.html
  templates/create_faculty_hub.html
  templates/createfacultyhub.html
  templates/facultyhub.html
Labels: bug, documentation, feature, help wanted, question, not yet finished, fix

#67 v1.2.9_auth_profile (2024.05.05 21:22)
  __pycache__/db_functions.cpython-312.pyc
  app.py
  create_tables.py
  database.db
  db_functions.py
Labels: documentation, feature, not yet finished

#70 v1.3.0_UserControl_Faculty_Profile_SignUp 6/5/2024
  app.py
  database.db
  static/style.css
  templates/Faculty.html
  templates/admin.html
  templates/appointment_control.html
  templates/profile.html
  templates/signup.html
  templates/usercontrol.html
Labels: documentation, feature, done, tested

#71 v1.3.1_admin_fix <Fixed routing and database> (2024.05.07, 12:37)
  __pycache__/db_functions.cpython-312.pyc
  create_tables.py
  database.db
  templates/Faculty.html
  uploads/IMG_20240425_082142.jpg
  uploads/photo_2024-04-28_22-45-13.jpg
Labels: fixed

#73 v1.3.3_homefix_displayfacready <Revised Home & Fac Disp Ready> (2024.05.07, 16:34)
  app.py
  database.db
  templates/home.html
Labels: documentation, feature, question, not yet finished, tested

#74 v1.3.4_AppointmentPage_History_Profile 8/5/2024
  app.py
  static/myscripts.js
  static/style.css
  templates/about.html
  templates/appointment.html
  templates/appointment2.html
  templates/changepassword.html
  templates/history.html
  templates/profile.html
Labels: documentation, feature, done

#77 v1.3.5_admin_myfac <Functionable My Faculty> (2024.05.11, 0:10)
  app.py
  database.db
  templates/Faculty.html
  uploads/logan-sargeant-williams.jpg
Labels: bug, documentation, feature, help wanted, question, fix, tested

#79 v1.3.7_lecturer_pin <Pin Verification For Lec> (2024.05.12, 1:00)
  app.py
  database.db
  templates/signupflash.html
  templates/signupteacher.html
Labels: bug, documentation, feature, help wanted, not yet finished, fix

#81 V1.3.9_PagesBug_Fixed_JinjiaTemplated_FlashBug
  app.py
  static/myscripts.js
  static/style.css
  templates/Faculty.html
  templates/about.html
  templates/admin.html
  templates/appointment_control.html
  templates/changepassword.html
  templates/directory.html
  templates/history.html
  templates/home.html
  templates/invoice.html
  templates/login.html
  templates/profile.html
  templates/spam.html
  templates/usercontrol.html
Labels: bug, documentation, feature, not yet finished, fixed

#90 v1.3.11_user_id_profile <Session ID User Done> (2024.05.13, 1:15)
  .gitignore
  __pycache__/db_functions.cpython-311.pyc
  app.py
  templates/profile.html
Labels: documentation, feature, done, fixed, tested

#94 v1.3.12_signuplogic <Sign In & Log In Logic Changed> (2024.05.13, 16:36)
  .gitignore
  app.py
  database.db
  static/myscripts.js
  static/style.css
  templates/Faculty.html
  templates/about.html
  templates/admin.html
  templates/appointment_control.html
  templates/changepassword.html
  templates/directory.html
  templates/history.html
  templates/home.html
  templates/invoice.html
  templates/login.html
  templates/profile.html
  templates/spam.html
  templates/usercontrol.html
Labels: documentation, feature, done, fixed, tested

#95 v1.3.13_auth_fixed <Auth Logic Fixed> (2024.05.13, 17:05)
  __pycache__/db_functions.cpython-311.pyc
  app.py
  database.db
Labels: documentation, feature, fixed, tested

#99 v1.3.14_jinja2_tempted <Jinja Intergrated> (2024.05.14, 14:17)
  .gitignore
  __pycache__/db_functions.cpython-311.pyc
  app.py
  database.db
  db_functions.py
  static/myscripts.js
  static/style.css
  templates/Faculty.html
  templates/about.html
  templates/admin.html
  templates/appointment2.html
  templates/appointment_control.html
  templates/booking_history.html
  templates/changepassword.html
  templates/directory.html
  templates/history.html
  templates/home.html
  templates/invoice.html
  templates/login.html
  templates/profile.html
  templates/spam.html
  templates/usercontrol.html
Labels: documentation, feature, done, fixed, tested

#100 v1.3.15_admin_crud <Admin Control On CRUD> (2024.05.14, 14:32)
  app.py
Labels: documentation, done, tested

#102 v1.4.0_app_revised <Revised app.py> (2024.05.15)
  app.py
  create_tables.py
  database.db
Labels: done, fixed, tested

#104 v1.4.1_pageeditor <Page Editor at Homepage> (2024.05.18, 2:02)
  app.py
  templates/admin.html
  templates/adminpageeditor.html
Labels: feature, not yet finished

#105 v1.4.2_pageeditor <Page Editor is Functional from Admin> (2024.05.18,12:32)
  app.py
  templates/adminpageeditor.html
  templates/home.html
Labels: documentation, feature, done, tested

#106 v1.4.3_pageeditor_save <Page Editor w/ Save Feature> (2024.05.18, 15:06)
  app.py
  content.json
  templates/adminpageeditor.html
Labels: documentation, done, fixed, tested

#110 v1.5.0_pageeditor <Added More Function into Page Editor> (2024.05.25, 15:51)
  app.py
  content.json
  static/uploads/29a797972ea730a4ff4b26855e6afa3f.jpg
  static/uploads/EWZGvVHWsAUZIxY.jpg
  static/uploads/mqdefault.jpg
  templates/Faculty.html
  templates/adminpageeditor.html
  templates/createfacultyhub.html
  templates/facultyhub.html
  templates/home.html
  templates/usercontrol.html
Labels: documentation, feature, done, fixed, tested

#114 v1.5.3_lec_auth <Teacher Authentication> (2024.05.27, 18:18)
  app.py
  database.db
  templates/signup.html
  templates/signupteacher.html
Labels: documentation, feature, done, tested

#115 v1.5.4_lec_changepin <Changeble Teacher PIN> (2024.05.28, 14:08)
  app.py
  content.json
  database.db
  pin.json
  templates/adminpageeditor.html
  templates/signup.html
Labels: documentation, feature, done, tested

#117 v1.6.1_faculty_pp <Faculty Profile Pic> (2024.05.31, 6:05)
  app.py
  database.db
  static/faculty_pp/2022-04-23_224101.png
  static/faculty_pp/29a797972ea730a4ff4b26855e6afa3f.jpg
  static/faculty_pp/Screenshot_2021-07-18_222623.png
  static/faculty_pp/Screenshot_2021-07-18_232655.png
  static/faculty_pp/Screenshot_2021-09-11_184614.png
  static/faculty_pp/sddefault.jpg
  wsdcfvcsa.py
Labels: done, fixed, tested
